name: biomed0shot
channels:
  - conda-forge
  - huggingface
  - nvidia
  - pytorch
dependencies:
  - huggingface_hub=0.24.6
  - pandas=2.2.2
  - pip=24.2
  - python=3.10.14
  - scipy=1.13.1
  - pip:
    - accelerate==0.33.0
    - bitsandbytes==0.43.3
    - datasets==2.21.0
    - deepspeed==0.15.1
    - fire==0.7.0
    - gliner==0.2.16
    - ms-swift==2.5.0.post1
    - transformers==4.45.2

