#!/bin/bash
# InstructUIE needs the truth files generated by the benchmark_LLM.py script.
# This is to not double the code.

for dir in Benchmarking/outputs/gemini_1_5_pro/*; do
    for file in $dir/true*; do
        cp "$file" "Benchmarking/outputs/ZWK_InstructUIE/$(basename $dir)/$(basename $file)"
    done
done